/*
 * EXTI.h
 *
 *  Created on: Jul 8, 2023
 *      Author: adham
 */

#ifndef MCAL_EXTI_EXTI_H_
#define MCAL_EXTI_EXTI_H_

//-----------------------------
//Includes
#include"../../includes/std_macros.h"
#include"../../includes/std_types.h"
#include"../../includes/stm32_f103_x6.h"
//-----------------------------

//-----------------------------
//User type definitions (structures)
typedef struct
{
	uint16_t				EXTI_TNP_LINE 			;//@ref :EXTI LINES
	GPIOx_Registers_t*		GPIO_EXTI_PORT			;//@ref :GPIO Peripheral instants
	uint8_t					GPIO_PIN  				;//@ref :GPIO PIN NUMBER
	uint8_t					IVQ_IRQ_NUMBER			;//@ref :IRQ according to IVT

}EXTI_GPIO_MAPPING_t;

typedef struct
{
	EXTI_GPIO_MAPPING_t 	EXT_PIN_CONFIG            ;// This parameter must be set @EXTI_DEFINE
	uint8_t 				TRIGGER_CASE	          ;// This parameter must be set @TRIG_REF
	uint8_t					IRQ_EN					  ;// This parameter must be set @IRQ_STATE
	void 					(*PTR_CALLBACK_FUN)(void) ;// POINTER TO FUNC FOR CALLBCAK
}EXTI_Config_t;
//-----------------------------

/*======================================================
 * 													   *
 * 		        	MACROS CONFIG					   *
 * 				                                       *
 *======================================================
 */

//EXTI LINES
#define EXTI_LINE_0				0
#define EXTI_LINE_1				1
#define EXTI_LINE_2				2
#define EXTI_LINE_3				3
#define EXTI_LINE_4				4
#define EXTI_LINE_5				5
#define EXTI_LINE_6				6
#define EXTI_LINE_7				7
#define EXTI_LINE_8				8
#define EXTI_LINE_9			 	9
#define EXTI_LINE_10			10
#define EXTI_LINE_11			11
#define EXTI_LINE_12			12
#define EXTI_LINE_13			13
#define EXTI_LINE_14			14
#define EXTI_LINE_15			15

//@ref EXTI_DEFINE
//EXTI0
#define EXTI0PA0	(EXTI_GPIO_MAPPING_t){EXTI_LINE_0	, GPIOA , GPIO_PIN0 , EXTI0_IRQ}
#define EXTI0PB0	(EXTI_GPIO_MAPPING_t){EXTI_LINE_0	, GPIOB , GPIO_PIN0 , EXTI0_IRQ}
#define EXTI0PC0	(EXTI_GPIO_MAPPING_t){EXTI_LINE_0	, GPIOC , GPIO_PIN0 , EXTI0_IRQ}
#define EXTI0PD0	(EXTI_GPIO_MAPPING_t){EXTI_LINE_0	, GPIOD , GPIO_PIN0 , EXTI0_IRQ}
//EXTI1
#define EXTI1PA1	(EXTI_GPIO_MAPPING_t){EXTI_LINE_1	, GPIOA , GPIO_PIN1 , EXTI1_IRQ}
#define EXTI1PB1	(EXTI_GPIO_MAPPING_t){EXTI_LINE_1	, GPIOB , GPIO_PIN1 , EXTI1_IRQ}
#define EXTI1PC1	(EXTI_GPIO_MAPPING_t){EXTI_LINE_1	, GPIOC , GPIO_PIN1 , EXTI1_IRQ}
#define EXTI1PD1	(EXTI_GPIO_MAPPING_t){EXTI_LINE_1	, GPIOD , GPIO_PIN1 , EXTI1_IRQ}
//EXTI2
#define EXTI2PA2	(EXTI_GPIO_MAPPING_t){EXTI_LINE_2	, GPIOA , GPIO_PIN2 , EXTI2_IRQ}
#define EXTI2PB2	(EXTI_GPIO_MAPPING_t){EXTI_LINE_2	, GPIOB , GPIO_PIN2 , EXTI2_IRQ}
#define EXTI2PC2	(EXTI_GPIO_MAPPING_t){EXTI_LINE_2	, GPIOC , GPIO_PIN2 , EXTI2_IRQ}
#define EXTI2PD2	(EXTI_GPIO_MAPPING_t){EXTI_LINE_2	, GPIOD , GPIO_PIN2 , EXTI2_IRQ}
//EXT3
#define EXTI3PA3	(EXTI_GPIO_MAPPING_t){EXTI_LINE_3	, GPIOA , GPIO_PIN3 , EXTI3_IRQ}
#define EXTI3PB3	(EXTI_GPIO_MAPPING_t){EXTI_LINE_3	, GPIOB , GPIO_PIN3 , EXTI3_IRQ}
#define EXTI3PC3	(EXTI_GPIO_MAPPING_t){EXTI_LINE_3	, GPIOC , GPIO_PIN3 , EXTI3_IRQ}
#define EXTI3PD3	(EXTI_GPIO_MAPPING_t){EXTI_LINE_3	, GPIOD , GPIO_PIN3 , EXTI3_IRQ}
//EXTI4
#define EXTI4PA4	(EXTI_GPIO_MAPPING_t){EXTI_LINE_4	, GPIOA , GPIO_PIN4 , EXTI4_IRQ}
#define EXTI4PB4	(EXTI_GPIO_MAPPING_t){EXTI_LINE_4	, GPIOB , GPIO_PIN4 , EXTI4_IRQ}
#define EXTI4PC4	(EXTI_GPIO_MAPPING_t){EXTI_LINE_4	, GPIOC , GPIO_PIN4 , EXTI4_IRQ}
#define EXTI4PD4	(EXTI_GPIO_MAPPING_t){EXTI_LINE_4	, GPIOD , GPIO_PIN4 , EXTI4_IRQ}
//EXTI5
#define EXTI5PA5	(EXTI_GPIO_MAPPING_t){EXTI_LINE_5	, GPIOA , GPIO_PIN5 , EXTI5_IRQ}
#define EXTI5PB5	(EXTI_GPIO_MAPPING_t){EXTI_LINE_5	, GPIOB , GPIO_PIN5 , EXTI5_IRQ}
#define EXTI5PC5	(EXTI_GPIO_MAPPING_t){EXTI_LINE_5	, GPIOC , GPIO_PIN5 , EXTI5_IRQ}
#define EXTI5PD5	(EXTI_GPIO_MAPPING_t){EXTI_LINE_5	, GPIOD , GPIO_PIN5 , EXTI5_IRQ}
//EXTI6
#define EXTI6PA6	(EXTI_GPIO_MAPPING_t){EXTI_LINE_6	, GPIOA , GPIO_PIN6 , EXTI6_IRQ}
#define EXTI6PB6	(EXTI_GPIO_MAPPING_t){EXTI_LINE_6	, GPIOB , GPIO_PIN6 , EXTI6_IRQ}
#define EXTI6PC6	(EXTI_GPIO_MAPPING_t){EXTI_LINE_6	, GPIOC , GPIO_PIN6 , EXTI6_IRQ}
#define EXTI6PD6	(EXTI_GPIO_MAPPING_t){EXTI_LINE_6	, GPIOD , GPIO_PIN6 , EXTI6_IRQ}
//EXTI7
#define EXTI7PA7	(EXTI_GPIO_MAPPING_t){EXTI_LINE_7	, GPIOA , GPIO_PIN7 , EXTI7_IRQ}
#define EXTI7PB7	(EXTI_GPIO_MAPPING_t){EXTI_LINE_7	, GPIOB , GPIO_PIN7 , EXTI7_IRQ}
#define EXTI7PC7	(EXTI_GPIO_MAPPING_t){EXTI_LINE_7	, GPIOC , GPIO_PIN7 , EXTI7_IRQ}
#define EXTI7PD7	(EXTI_GPIO_MAPPING_t){EXTI_LINE_7	, GPIOD , GPIO_PIN7 , EXTI7_IRQ}
//EXTI8
#define EXTI8PA8	(EXTI_GPIO_MAPPING_t){EXTI_LINE_8	, GPIOA , GPIO_PIN8 , EXTI8_IRQ}
#define EXTI8PB8	(EXTI_GPIO_MAPPING_t){EXTI_LINE_8	, GPIOB , GPIO_PIN8 , EXTI8_IRQ}
#define EXTI8PC8	(EXTI_GPIO_MAPPING_t){EXTI_LINE_8	, GPIOC , GPIO_PIN8 , EXTI8_IRQ}
#define EXTI8PD8	(EXTI_GPIO_MAPPING_t){EXTI_LINE_8	, GPIOD , GPIO_PIN8 , EXTI8_IRQ}
//EXTI9
#define EXTI9PA9	(EXTI_GPIO_MAPPING_t){EXTI_LINE_9	, GPIOA , GPIO_PIN9 , EXTI9_IRQ}
#define EXTI9PB9	(EXTI_GPIO_MAPPING_t){EXTI_LINE_9	, GPIOB , GPIO_PIN9 , EXTI9_IRQ}
#define EXTI9PC9	(EXTI_GPIO_MAPPING_t){EXTI_LINE_9	, GPIOC , GPIO_PIN9 , EXTI9_IRQ}
#define EXTI9PD9	(EXTI_GPIO_MAPPING_t){EXTI_LINE_9	, GPIOD , GPIO_PIN9 , EXTI9_IRQ}
//EXTI10
#define EXTI10PA10	(EXTI_GPIO_MAPPING_t){EXTI_LINE_10	, GPIOA , GPIO_PIN10 , EXTI10_IRQ}
#define EXTI10PB10	(EXTI_GPIO_MAPPING_t){EXTI_LINE_10	, GPIOB , GPIO_PIN10 , EXTI10_IRQ}
#define EXTI10PC10	(EXTI_GPIO_MAPPING_t){EXTI_LINE_10	, GPIOC , GPIO_PIN10 , EXTI10_IRQ}
#define EXTI10PD10	(EXTI_GPIO_MAPPING_t){EXTI_LINE_10	, GPIOD , GPIO_PIN10 , EXTI10_IRQ}
//EXTI11
#define EXTI11PA11	(EXTI_GPIO_MAPPING_t){EXTI_LINE_11	, GPIOA , GPIO_PIN11 , EXTI11_IRQ}
#define EXTI11PB11	(EXTI_GPIO_MAPPING_t){EXTI_LINE_11	, GPIOB , GPIO_PIN11 , EXTI11_IRQ}
#define EXTI11PC11	(EXTI_GPIO_MAPPING_t){EXTI_LINE_11	, GPIOC , GPIO_PIN11 , EXTI11_IRQ}
#define EXTI11PD11	(EXTI_GPIO_MAPPING_t){EXTI_LINE_11	, GPIOD , GPIO_PIN11 , EXTI11_IRQ}
//EXTI12
#define EXTI12PA12	(EXTI_GPIO_MAPPING_t){EXTI_LINE_12	, GPIOA , GPIO_PIN12 , EXTI12_IRQ}
#define EXTI12PB12	(EXTI_GPIO_MAPPING_t){EXTI_LINE_12	, GPIOB , GPIO_PIN12 , EXTI12_IRQ}
#define EXTI12PC12	(EXTI_GPIO_MAPPING_t){EXTI_LINE_12	, GPIOC , GPIO_PIN12 , EXTI12_IRQ}
#define EXTI12PD12	(EXTI_GPIO_MAPPING_t){EXTI_LINE_12	, GPIOD , GPIO_PIN12 , EXTI12_IRQ}
//EXTI13
#define EXTI13PA13	(EXTI_GPIO_MAPPING_t){EXTI_LINE_13	, GPIOA , GPIO_PIN13 , EXTI13_IRQ}
#define EXTI13PB13	(EXTI_GPIO_MAPPING_t){EXTI_LINE_13	, GPIOB , GPIO_PIN13 , EXTI13_IRQ}
#define EXTI13PC13	(EXTI_GPIO_MAPPING_t){EXTI_LINE_13	, GPIOC , GPIO_PIN13 , EXTI13_IRQ}
#define EXTI13PD13	(EXTI_GPIO_MAPPING_t){EXTI_LINE_13	, GPIOD , GPIO_PIN13 , EXTI13_IRQ}
//EXTI14
#define EXTI14PA14	(EXTI_GPIO_MAPPING_t){EXTI_LINE_14	, GPIOA , GPIO_PIN14 , EXTI14_IRQ}
#define EXTI14PB14	(EXTI_GPIO_MAPPING_t){EXTI_LINE_14	, GPIOB , GPIO_PIN14 , EXTI14_IRQ}
#define EXTI14PC14	(EXTI_GPIO_MAPPING_t){EXTI_LINE_14	, GPIOC , GPIO_PIN14 , EXTI14_IRQ}
#define EXTI14PD14	(EXTI_GPIO_MAPPING_t){EXTI_LINE_14	, GPIOD , GPIO_PIN14 , EXTI14_IRQ}
//EXTI15
#define EXTI15PA15	(EXTI_GPIO_MAPPING_t){EXTI_LINE_15	, GPIOA , GPIO_PIN15, EXTI15_IRQ}
#define EXTI15PB15	(EXTI_GPIO_MAPPING_t){EXTI_LINE_15	, GPIOB , GPIO_PIN15, EXTI15_IRQ}
#define EXTI15PC15	(EXTI_GPIO_MAPPING_t){EXTI_LINE_15	, GPIOC , GPIO_PIN15, EXTI15_IRQ}
#define EXTI15PD15	(EXTI_GPIO_MAPPING_t){EXTI_LINE_15	, GPIOD , GPIO_PIN15, EXTI15_IRQ}



//@REF TRIGG_REF
#define EXTI_RISING_EDGE			0
#define EXTI_FALLING_EDGE			1
#define EXTI_RISINGANDFALLING_EDGE	2

//@IRQ_STATE
#define IRQ_DISABLE		0
#define IRQ_ENABLE		1

//-------------------------------------------

/*======================================================
 * 													   *
 * 			APIs Supported by "MCAL EXIT DRIVER"       *
 * 				                                       *
 *======================================================
 */
void MCAL_EXTI_Init(EXTI_Config_t *Config);
void MCAL_EXTI_DeInit(void);
void MCAL_EXTI_Update(EXTI_Config_t *Config);
#endif /* MCAL_EXTI_EXTI_H_ */
